name: Generate ASCII Artwork

on:
    push
jobs:
    build_job:
        runs-on: ubuntu-latest
        name: A build job to cowsay
        steps:
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: excute Cowsay
          run: cowsay -f dragon "Run , i am the dragon,,,, RAWR" >> dragon.txt

        - name: upload the dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        name: A test job to cowsay
        steps:
        - name: download the dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: test a file
          run: grep -i "dragon" dragon.txt
        
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        name: A deploy job to cowsay
        steps:
        - name: download the dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Read a file
          run: cat dragon.txt
    
        - name: excute Cowsay
          run: echo Deploying ......
