name: Generate ASCII Artwork

on:
    push
jobs:
        test:
          runs-on: ubuntu-latest
          name: A test job to cowsay
          steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: lsit Repo Files
            run: ls ltra
          - name: Excuting shell script
            run: ./ascii-script.sh